# Generated by Django 3.0.7 on 2020-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=10000, verbose_name='KeyWord')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Manifest',
                'verbose_name_plural': 'Manifests',
            },
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AddField(
            model_name='manifest',
            name='resources',
            field=models.ManyToManyField(to='request.Resource', verbose_name='Resources'),
        ),
        migrations.AddField(
            model_name='config',
            name='platforms',
            field=models.ManyToManyField(to='request.Platform', verbose_name='Platform'),
        ),
    ]
