# Generated by Django 3.0.7 on 2020-07-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20200706_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='platforms',
        ),
        migrations.AddField(
            model_name='config',
            name='reousrces',
            field=models.ManyToManyField(blank=True, to='request.Resource', verbose_name='Resources'),
        ),
    ]
