# Generated by Django 3.0.7 on 2020-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20200706_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='request.Platform', verbose_name='Platforms'),
        ),
    ]
